export default {
  uk: {
    headline: "Tired of all the drawbacks of the Danish taxi system but need a ride?",
    listHeader: "With Jubi Rides you are guaranteed:",
    listItem1p: "Experienced and skilled drivers.",
    listItem1s: "Only riders with past experience are allowed to sign-up.",
    listItem2p: "Convenient.",
    listItem2s: "Look for rides using the mobile App.",
    listItem3p: "Low cost. Affordable.",
    listItem3s: "Know the final price when selecting your ride. Pay by creditcard or MobilePay",
    soon: "If you interested in contributing to this startup, contact me by email.",
    interested: "",
    topNavBtn: "Sign up to become a driver",
    dialogTitle: "Send the following information to",
    dialogListItem1p: "Personal information",
    dialogListItem1s: "Name, address, year born, etc.",
    dialogListItem2p: "All relevant driving experience",
    dialogListItem2s: "Assets that prove your skills.",
    dialogListItem3p: "Cover letter",
    dialogListItem3s: "Explanation of why you'd like to become a driver at Jubi",
    dialogListItem4p: "Photo",
    dialogListItem4s: "A newly shot photograph of you",
    dialogListItem5p: "Car information",
    dialogListItem5s: "All relevant car information such as brand, km rode, color, current state",
    dialogBtn: "Close this window",
    contact: "Contact: "
  },
  dk: {
    headline: "Træt af alle de ulemper der kommer ved at bestille en dansk taxi?",
    listHeader: "Med Jubi Rides er du garanteret:",
    listItem1p: "Erfarne og dygtige chauffører.",
    listItem1s: "Kun chauffører med tidligere kørsel erfaring.",
    listItem2p: "Nemt og enkelt.",
    listItem2s: "Kig efter et lift med den simple og lynhurtige app.",
    listItem3p: "Lav og overkommelig pris.",
    listItem3s: "Se det samlede beløb når du bestiller et lift. Betal med kort eller MobilePay.",
    soon: "Hvis du interesseret i den her startup ide, kontakt mig gerne på mail.",
    interested: "",
    topNavBtn: "Skriv dig op og bliv chauffør",
    dialogTitle: "Send følgende information til",
    dialogListItem1p: "Personlig information",
    dialogListItem1s: "Navn, addresse, født, osv.",
    dialogListItem2p: "Alt relevant kørsel erfaring",
    dialogListItem2s: "Bilag der kan argumentere for dine egenskaber.",
    dialogListItem3p: "Cover brev",
    dialogListItem3s: "Forklaring af hvorfor du gerne vil være chauffør hos Jubi",
    dialogListItem4p: "Foto",
    dialogListItem4s: "Et billede af dig taget fornylig",
    dialogListItem5p: "Bil information",
    dialogListItem5s: "Alt relevant bil information såsom mærke, km kørt, farve, nuværende stand",
    dialogBtn: "Luk dette vindue",
    contact: "Kontakt: "
  }
};
